from datetime import datetime

from sqlalchemy import JSON, DateTime, ForeignKey, Index, BIGINT, String, VARCHAR
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.sqlalchemy.base import Base




class CommonCharacterORM(Base):
    __tablename__ = "common_characters"
    id: Mapped[str] = mapped_column(String, primary_key=True)

    # 常用字形
    form: Mapped[str] = mapped_column(String, nullable=False, index=True)
    # 描述, like why the common char is used
    description: Mapped[str] = mapped_column(String, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)


class StandardCharacterORM(Base):
    __tablename__ = "standard_characters"
    id: Mapped[str] = mapped_column(String, primary_key=True)

    # 標準字形
    form: Mapped[str] = mapped_column(String, nullable=False, index=True)
    common_character_id: Mapped[str] = mapped_column(String, nullable=True, index=True)

    # 描述
    description: Mapped[str] = mapped_column(String, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)


class StandardWordORM(Base):
    __tablename__ = "words"
    id: Mapped[str] = mapped_column(String, primary_key=True)
    # 標準字形
    form: Mapped[str] = mapped_column(String, nullable=False, index=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)


class CommonWordORM(Base):
    __tablename__ = "common_words"
    id: Mapped[str] = mapped_column(String, primary_key=True)
    # 常用字形
    form: Mapped[str] = mapped_column(String, nullable=False, index=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)


class PronounciationORM(Base):
    __tablename__ = "pronounciations"
    id: Mapped[str] = mapped_column(String, primary_key=True)
    charactor_id: Mapped[str] = mapped_column(String, nullable=False)

    # 標準音，普通話拼音
    pinyin: Mapped[str] = mapped_column(String, nullable=True, index=True)
    # 標準音，吳語拼音
    wu: Mapped[str] = mapped_column(String, nullable=True)
    # 標準音，廣韻
    canton: Mapped[str] = mapped_column(String, nullable=True)
    # 標準音，國際音標
    phonetic: Mapped[str] = mapped_column(String, nullable=True)

    # 描述
    description: Mapped[str] = mapped_column(String, nullable=True)

    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class SourceORM(Base):
    # 文獻索引
    __tablename__ = "sources"
    id: Mapped[str] = mapped_column(String, primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(String, nullable=True)
    # generated by the system
    # cover_image_key: Mapped[str] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)


class SourceWordAssociationORM(Base):
    __tablename__ = "source_word_associations"
    id: Mapped[str] = mapped_column(String, primary_key=True)
    source_id: Mapped[str] = mapped_column(
        String, ForeignKey("sources.id"), nullable=False
    )
    word_id: Mapped[str] = mapped_column(String, ForeignKey("words.id"), nullable=False)
    content: Mapped[dict] = mapped_column(JSON, nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)


class SourceCharacterAssociationORM(Base):
    __tablename__ = "source_character_associations"
    id: Mapped[str] = mapped_column(String, primary_key=True)
    source_id: Mapped[str] = mapped_column(
        String, ForeignKey("sources.id"), nullable=False
    )
    character_id: Mapped[str] = mapped_column(
        String, ForeignKey("characters.id"), nullable=False
    )
    content: Mapped[dict] = mapped_column(JSON, nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)
